name: Release

permissions:
  contents: write
  id-token: write
  attestations: write

on:
  push:
    tags:
      - '[0-9]+.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: universal-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Verify assets integrity
        shell: bash
        run: |
          echo "4b5c8507ff16f7712e28e0f635fd783f2a8ba7c912f82d86223a90f3656a2395  dist/roms/apogee.rom" > SHA256SUMS
          echo "a71d0166f73952675db15088545276cf39805cab34f9c94f28de50931f8ed99f  dist/fonts/sga.bin" >> SHA256SUMS
          echo "262b653bb227ae5544e35e3fa0707dc43f06ebd36f167658683fd65ec239c788  tests/assets/ducks.rka" >> SHA256SUMS
          echo "737b8a71eea220794180748033dca32e01e06e1ce597dddd51f96788a19e4d48  tests/assets/dvigalka.rka" >> SHA256SUMS
          echo "7bed714c5f1975aadf7f47de5b82a6b3a972a6216fd66784187476a86b6b0814  tests/assets/kindzadza.rka" >> SHA256SUMS
          echo "cc553a0c36aca27c4ba1ab27bdeba0073b9332a966bc5f95593c3dc16b66223b  tests/assets/kletavt.rka" >> SHA256SUMS
          echo "95e2edd76cf15ef3bf8e22c1e85a1be9691f0be2ac764d21275e1c0594bdadca  tests/assets/rc.rka" >> SHA256SUMS
          echo "42bc4bc92475d4e84cf1b145d0fcea6d104ec2da421cc6880ea8d14fdfaeae2c  tests/assets/robocop.rka" >> SHA256SUMS
          echo "2f34aa96004ecec170de4e616c2257657d9eee7af9feeb549cf53ebe27e39d1f  tests/assets/tia2.rka" >> SHA256SUMS
          sha256sum --check SHA256SUMS || shasum -a 256 -c SHA256SUMS
      - name: Update Rust
        run: rustup update stable
      - name: Install ALSA
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev
      - uses: taiki-e/upload-rust-binary-action@v1
        id: upload
        with:
          bin: apogee
          target: ${{ matrix.target }}
          checksum: sha256
          all-features: false
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/attest@v4
        with:
          subject-checksums: ${{ steps.upload.outputs.sha256 }}

  update-homebrew:
      needs: upload-assets
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v6
          with:
            submodules: recursive
        - name: Trigger tap update
          run: |
            gh workflow run update-formula.yml \
              --repo coignard/homebrew-tap \
              --field version=${{ github.ref_name }}
          env:
            GH_TOKEN: ${{ secrets.TAP_TOKEN }}
